// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCly2XiX_sHK_bmK5EsecfoH27LlKbimns',
    appId: '1:1074986358711:web:eba1a9e82d7c34a3bc3a32',
    messagingSenderId: '1074986358711',
    projectId: 'takyeem-f4fee',
    authDomain: 'takyeem-f4fee.firebaseapp.com',
    storageBucket: 'takyeem-f4fee.firebasestorage.app',
    measurementId: 'G-L0HSTJ6CXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVcTgK-_nCz90OrO_Kdxpxxs9g0Z0AspU',
    appId: '1:1074986358711:android:13e7ac05a41902e3bc3a32',
    messagingSenderId: '1074986358711',
    projectId: 'takyeem-f4fee',
    storageBucket: 'takyeem-f4fee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjeiYzwfQIX5rMWKP8IpkdGrS4nhgWkdw',
    appId: '1:1074986358711:ios:f9bdd07a5ed744afbc3a32',
    messagingSenderId: '1074986358711',
    projectId: 'takyeem-f4fee',
    storageBucket: 'takyeem-f4fee.firebasestorage.app',
    iosBundleId: 'com.example.takyeem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjeiYzwfQIX5rMWKP8IpkdGrS4nhgWkdw',
    appId: '1:1074986358711:ios:f9bdd07a5ed744afbc3a32',
    messagingSenderId: '1074986358711',
    projectId: 'takyeem-f4fee',
    storageBucket: 'takyeem-f4fee.firebasestorage.app',
    iosBundleId: 'com.example.takyeem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCly2XiX_sHK_bmK5EsecfoH27LlKbimns',
    appId: '1:1074986358711:web:461c2412a139dd96bc3a32',
    messagingSenderId: '1074986358711',
    projectId: 'takyeem-f4fee',
    authDomain: 'takyeem-f4fee.firebaseapp.com',
    storageBucket: 'takyeem-f4fee.firebasestorage.app',
    measurementId: 'G-CRLVGEXTY7',
  );
}
